[package]
name = "brainfuckyou"
version = "0.1.0"
authors = ["Joey Gibson <joey@joeygibson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
