name: build

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: cargo test --verbose
      - name: Build for release
        run: cargo build --verbose --release
